// apps/svelte/src/lib/components/Video.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	export let width: number;
	export let height: number;
	export let onVideoReady: (element: HTMLVideoElement) => void;

	let videoElement: HTMLVideoElement;

	onMount(() => {
		videoElement.style = `width:${width}px; height:${height}px;`;

		onVideoReady(videoElement);
	});
</script>

<video class="border1px" bind:this={videoElement} autoplay playsinline></video>

// apps/nextjs/src/components/Video.tsx
'use client';

import { useEffect, useRef } from 'react';

interface VideoProps {
	onVideoReady: (element: HTMLVideoElement | null) => void;
}

export default function Video({ onVideoReady }: VideoProps) {
	const videoRef = useRef<HTMLVideoElement>(null);

	useEffect(() => {
		if (videoRef.current) {
			onVideoReady(videoRef.current);
		}
	}, [onVideoReady]);

	return <video ref={videoRef} autoPlay playsInline />;
}
